steps:
    - name: node:14.15.1
      entrypoint: npm
      args: ["install"]

    - name: node:14.15.1
      entrypoint: npm
      args: ["run", "create-env"]
      env:
          - "API_BASE_URL=${_API_BASE_URL}"
          - "APP_BASE_URL=${_APP_BASE_URL}"
          - "APP_MODE=${_APP_MODE}"
          - "BACKEND_BASE_URL=${_BACKEND_BASE_URL}"
          - "EMPLOYER_BASE_URL=${_EMPLOYER_BASE_URL}"
          - "NUXT_PORT=${_NUXT_PORT}"

    - name: node:14.15.1
      entrypoint: npm
      args: ["run", "build"]

    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy"]

timeout: "1600s"
